#!/usr/bin/python3
import sys
import time


def open_file(file_name):
    try:
        with open(file_name, "r", encoding="utf-8") as file:
            lines = file.readlines()
        number_to_factor = [int(line.strip()) for line in lines]
        return number_to_factor
    except FileNotFoundError:
        print(f"File '{file_name}' not found.")
        sys.exit(1)
    except ValueError:
        print("Invalid input in the file. Please make sure all lines contain valid integers.")
        sys.exit(1)

def factor_and_test(n):
    for i in range(2, n):
        if n % i == 0:
            print(f"{n} = {n // i} * {i}")
            break
    else:
        # If no factors were found, it's a prime number
        print(f"{n} is a prime number.")

def fac_list(test):
    for i in test:
        factor_and_test(i)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python script_name.py <file>")
        sys.exit(1)

    input_file = sys.argv[1]
    numbers = open_file(input_file)
    fac_list(numbers)


    start_time = time.time()
    open_file(input_file)
    elapsed_time = time.time() - start_time

    if elapsed_time > 5:
        print("Execution time exceeded 5 seconds. Terminating.")
        sys.exit(1)
